; ─────────────────────────────────────────────────────────────────────────────
; SEN66 Monitor — Phase 2
; ─────────────────────────────────────────────────────────────────────────────
[env:pico_w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 1m
 
lib_deps =
    jgromes/RadioLib @ ^6
    sensirion/Sensirion I2C SEN66
    bblanchon/ArduinoJson @ ^7
 
monitor_speed = 115200
monitor_filters = direct